### ISSUE TITLE
Problems with spreadsheet

### ISSUE THREAD

**Issue by uli6666** [looooo/freecad.gears#116]
Hallo,
I don´t know much about Freecad and had some Problems
I found a wonderful design (https://github.com/fellesverkstedet/fabricatable-machines/blob/master/Module%20development/herring-axis/alu_extrusion_herring_rack.FCStd)  that I want you use. 

If I opened it everything seems to be ok, but if a changed the length in the spreadsheet from 120mm to maybe 200mm I get the following errors:

00:45:04 Traceback (most recent call last):
File "C:\Users\win10\AppData\Roaming\FreeCAD\Mod\freecad.gears\freecad\gears\features.py", line 106, in execute
gear_shape = self.generate_gear_shape(fp)
File "C:\Users\win10\AppData\Roaming\FreeCAD\Mod\freecad.gears\freecad\gears\features.py", line 567, in generate_gear_shape
c = obj.clearance
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'clearance'
00:45:04 Traceback (most recent call last):
File "C:\Users\win10\AppData\Roaming\FreeCAD\Mod\freecad.gears\freecad\gears\features.py", line 106, in execute
gear_shape = self.generate_gear_shape(fp)
File "C:\Users\win10\AppData\Roaming\FreeCAD\Mod\freecad.gears\freecad\gears\features.py", line 234, in generate_gear_shape
fp.da = "{}mm".format(fp.gear.da)
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'da'

I do know nothing about Freecad, please can you help me out.
Thank you in advance

**Comment by looooo** [comment]
I guess this was designed with an older version of freecad.gears. you need to redesign the gear and replace the old gear. But I just found another error with computing `dw`... :(
