### ISSUE TITLE
Deleting a gear connector spills some errors in the log

### ISSUE THREAD

**Issue by mbait** [looooo/freecad.gears#130]
```
11:19:07  Traceback (most recent call last):
  File "/home/mbait/snap/freecad/common/Mod/freecad.gears/./freecad/gears/connector.py", line 63, in onChanged
    if isinstance(fp.master_gear.Proxy, InvoluteGear) and isinstance(fp.slave_gear.Proxy, InvoluteGear):
<class 'AttributeError'>: 'NoneType' object has no attribute 'Proxy'
11:19:07  Traceback (most recent call last):
  File "/home/mbait/snap/freecad/common/Mod/freecad.gears/./freecad/gears/connector.py", line 63, in onChanged
    if isinstance(fp.master_gear.Proxy, InvoluteGear) and isinstance(fp.slave_gear.Proxy, InvoluteGear):
<class 'AttributeError'>: 'NoneType' object has no attribute 'Proxy'
```

**Comment by Unicod3r** [comment]
Same problem.
