### ISSUE TITLE
Start of workbench is not possible

### ISSUE THREAD

**Issue by schoenid** [looooo/freecad.gears#170]
After starting the gears workbench an error occurs:
![image](https://github.com/looooo/freecad.gears/assets/15383666/489438aa-32b2-44e3-8bb3-2231d926178e)

![image](https://github.com/looooo/freecad.gears/assets/15383666/89994d18-a686-417c-9dd2-c59945de5e52)

Log:
```
03:11:30  invalid syntax (process.py, line 262)
03:11:30  Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\FreeCAD\Mod\freecad.gears\.\freecad\gears\init_gui.py", line 114, in Initialize
    from .commands import (
  File "E:\Programme\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\me\AppData\Roaming\FreeCAD\Mod\freecad.gears\.\freecad\gears\commands.py", line 27, in <module>
    from .timinggear_t import TimingGearT
  File "E:\Programme\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\me\AppData\Roaming\FreeCAD\Mod\freecad.gears\.\freecad\gears\timinggear_t.py", line 22, in <module>
    from scipy import optimize
  File "E:\Programme\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Programme\FreeCAD 0.21\bin\lib\site-packages\scipy\optimize\__init__.py", line 387, in <module>
    from .optimize import *
  File "E:\Programme\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Programme\FreeCAD 0.21\bin\lib\site-packages\scipy\optimize\optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "E:\Programme\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Programme\FreeCAD 0.21\bin\lib\site-packages\scipy\optimize\_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "E:\Programme\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\
```

FreeCAD info:
```
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * A2plus 0.4.65
  * ArchTextures
  * Assembly3 0.12.2
  * Assembly4 0.50.15
  * BOLTSFC
  * CADExchanger
  * CurvedShapes 1.0.9
  * Curves 0.6.40
  * Defeaturing 1.2.2
  * Design456 0.0.1
  * dodo 1.0.1
  * EM 2.1.1
  * fasteners 0.5.24
  * flamingo
  * freecad.gears 1.2.0
  * Help 1.0.3
  * kicadStepUpMod 11.2.4
  * MakerWorkbench 1.0.1
  * Manipulator 1.5.7
  * offline-documentation 1.0.0-alpha
  * offline-documentation.backup1720568008.0020056 1.0.0-alpha (Disabled)
  * ose-piping
  * parts_library
  * pcb 6.2023.1
  * Pyramids-and-Polyhedrons
  * RemBench
  * retr3d
  * sheetmetal 0.4.22
  * Silk 0.1.5
  * slic3r-tools
  * ThreadProfile 1.90.0
  * workfeature
  * workfeature-macro
[/code]
```

**Comment by looooo** [comment]
Not sure if this is related to this workbench. The traceback mention shiboken2. Did you compile freecad yourself?

**Comment by schoenid** [comment]
I've installed FreeCAD from Website (Windows installation package).
All other workbenches are working fine without errors.
Packages were instaled using the Addon-Manager on FreeCAD menu tools (Werkzeuge).

**Comment by schoenid** [comment]
Because I've got a dual boot system, I've checked it on Ubuntu 22.04.
There is no problem.
Unfortunately, the Ubuntu system is not usable for me, because I'm working on network drives, and the cifs package (required for samba networking) has some bugs, which makes it impossible for me to use it.

However, here my FreeCAD info from Ubuntu:
```
[code]
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) Snap 908
Build type: Release
Branch: tag: 0.21.2
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods:
  * pyrate (Disabled)
  * Glass
  * CadbaseLibrary 0.3.0
  * Defeaturing 1.2.2
  * Design456 0.0.1
  * ModernUI (Disabled)
  * pcb 6.2023.1
  * kicadStepUpMod 10.23.2
  * CurvedShapes 1.0.5
  * parts_library
  * Curves 0.6.24
  * Assembly4 0.50.9
  * freecad.gears 1.2.0
  * fasteners 0.5.13
  * frame 0.1.1
  * 3D_Printing_Tools
[/code]
```

I'm not familiar with Python, so I'm not able to find the problem on the Windows side.

**Comment by Syres916** [comment]
When I see _Scipy_ or _Numpy_ errors it usually leads to the versions having been upgraded individually and not as a pair. 

A very similar issue was logged for the Curves Wb, see https://github.com/tomate44/CurvesWB/issues/124 for the steps to get a resolution. Basically the root cause was the LibPack used as the basis to build the Windows Installer for 0.21.x is now out-of-date with regard to some of the included libraries so when FreeCAD 1.0 is released it will have a new LibPack with all recent libraries but it still requires the user to do some library management over time.

**Comment by EmEiBee** [comment]
... but that doesn't really help if you are neither a programmer nor know what should/must be updated where...

**Comment by schoenid** [comment]
In the meantime I did an update of my Windows FreeCAD installation, with the result, that Gear won't work there too.
I simply give up and will not use this anymore. I can import STEP models of the gears I need.

**Comment by schoenid** [comment]
> Keep open ?

No.
I did an Update of FreeCAD to 1.0 yesterday.
The Gear workbench is fully working.
Thanks.

**Comment by schoenid** [comment]
Addendum:

The Fix to solve this problem is an Upgrade to FreeCAD v1.0.0
